#!/bin/bash

echo "[check] minikube..."
if ! command -v minikube &> /dev/null
then
    echo "Minikube not found. Please install it and re-run."
    exit 1
fi

echo "[start] Starting Minikube..."
minikube start

echo "[verify] Checking cluster info..."
kubectl cluster-info

echo "[pods] Listing all pods..."
kubectl get pods --all-namespaces
