# chats/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ConversationViewSet, MessageViewSet

# Create a router to automatically handle URL patterns for your ViewSets
router = DefaultRouter()
router.register(r'conversations', ConversationViewSet) # Registers /api/conversations/ and /api/conversations/<id>/
router.register(r'messages', MessageViewSet)       # Registers /api/messages/ and /api/messages/<id>/

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]